- name: Install Munge
  hosts: cluster, local
  tags: install_munge
  become: true

  tasks:
    - name: Create Munge user on all systems
      ansible.builtin.user:
        name: munge
        shell: /usr/sbin/nologin


    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        prefix: munge
      register: munge_work_dir


    - name: Install Munge from github
      ansible.builtin.git:
        repo: https://github.com/dun/munge.git
        dest: "{{ munge_work_dir.path }}"

    - name: Bootstrap Munge
      ansible.builtin.command: ./bootstrap
      args: 
        chdir: "{{ munge_work_dir.path }}"

    - name: Configure Munge
      shell: |
        ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --runstatedir=/run
      args:
        chdir: "{{ munge_work_dir.path }}"
        
    - name: Make Munge
      ansible.builtin.command: make
      args:
        chdir: "{{ munge_work_dir.path }}"

    - name: Make Install Munge
      ansible.builtin.command: make install
      args: 
        chdir: "{{ munge_work_dir.path }}"

    - name: Set Munge directory permissions
      ansible.builtin.file:
        path: /etc/munge
        owner: munge
        group: munge
        mode: '0700'
        state: directory

    - name: Delete work dir
      ansible.builtin.file:
        path: "{{ munge_work_dir.path }}"
        state: absent

- name: Setup Munge Keys
  tags: keys
  become: true
  hosts: cluster, local
  tasks:

    - name: Slurp Munge Key
      delegate_to: localhost
      ansible.builtin.slurp:
        src: /etc/munge/munge.key
      register: munge_key_content
      run_once: true

    - name: Create Munge Key on local
      delegate_to: localhost
      become_user: munge
      shell: mungekey --verbose
      args:
        creates: /etc/munge/munge.key
        chdir: /usr/sbin

    - name: Check if key was created
      delegate_to: localhost
      ansible.builtin.stat:
        path: /etc/munge/munge.key
      register: key_exists

    - name: Copy to control directory
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ munge_key_content.content | b64decode }}"
        dest: /home/control/ansible/munge.key
        owner: control
        group: control
        mode: '0644'
      run_once: true

    - name: Distribute munge key
      ansible.builtin.copy:
        src: /home/control/ansible/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'
      when: key_exists.stat.exists

    - name: Delete temp key
      delegate_to: localhost
      ansible.builtin.file:
        path: /home/control/ansible/munge.key
        state: absent

- name: Start Munge
  tags: start_munge
  hosts: cluster, local
  tasks:

    - name: Start Munge Service
      become_user: munge
      ansible.builtin.service:
        name: munge
        state: started
        enabled: yes

